import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MuiProvider from "@/providers/muiProvider";
import StoreProvider from "@/providers/storeProvider";
import ResponsiveAppBar from "@/components/mui/NavBar";
import HtmlClientSide from "@/components/layoutClientSide/htmlClientSide";
import CssBaseline from "@mui/material/CssBaseline";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.clear();
  return (
    <StoreProvider>
      <MuiProvider>
        <HtmlClientSide>
          <ResponsiveAppBar />
          {children}
        </HtmlClientSide>
      </MuiProvider>
    </StoreProvider>
  );
}
